### ISSUE TITLE
Datenpunkttyp boolean

### ISSUE THREAD

**Issue by boeckp** [ioBroker/ioBroker.scheduler#17]
Können auch boolean State verwendet werden?
Mir werden sie nicht zum auswählen angezeigt.

**Comment by GermanBluefox** [comment]
Man muss Typ umschalten:
![image](https://user-images.githubusercontent.com/4582016/133891751-8d976603-676b-4a2d-8781-cae621d47240.png)

**Comment by boeckp** [comment]
Jetzt habe ich es auch gefunden.
Auf dem iPad muss die Seitenleiste ausgeblendet werden.
Sonst werden die Optionen alle nach unten und Teilweise übereinander verschoben.
