### ISSUE TITLE
File index.html not found

### ISSUE THREAD

**Issue by Castlehub** [ioBroker/ioBroker.scheduler#20]
Hallo Bluefox,
ich habe gerade den Adapter ausprobieren wollen und komme aber leider nach der Installation nicht in die Konfiguration. Es wird mir auf der Seite nur folgende Info angezeigt „File index.html not found“. Gibt es dafür eine Lösung?

MfG

**Comment by Apollon77** [comment]
Interesting. Try "iobroker upload scheduler"

**Comment by Castlehub** [comment]
Leider

> Interessant. Versuchen Sie "iobroker Upload Scheduler"

**Comment by Castlehub** [comment]
> Leider
> 
> > Interessant. Versuchen Sie "iobroker Upload Scheduler"

Leider ergab es die selbe Meldung. Bei mir läuft der IoB  mit Node.js v14.17.6, kann dies die Ursache sein?

**Comment by Apollon77** [comment]
Nein sollte es nicht. Aber warum closed wenn es noch offen ist? Es ist eher die Frage welche Admin version läuft? Also das sieht mir eher bei Dir nach Admin 3 aus ... aktuell ist Admin5!

**Comment by Castlehub** [comment]
Sorry, sollte nicht geschlossen werden. Bei mir läuft der Admin in der v. 5.1.25

**Comment by VLGorskij** [comment]
Hello, exactly the same error - „File index.html not found“.
Tried "iobroker upload scheduler" - to no avail

**Comment by VLGorskij** [comment]
Clarification - the described error appears when configuring the admin adapter to "use the old interface". 
Everything works with the new interface!

**Comment by Castlehub** [comment]
> Klarstellung - der beschriebene Fehler tritt bei der Konfiguration des Admin-Adapters auf, um "die alte Schnittstelle zu verwenden".
> Alles funktioniert mit der neuen Oberfläche!

Das ist des Fehlers Lösung. Danke
