### ISSUE TITLE
Not all data types available for timeclock

### ISSUE THREAD

**Issue by RESDE** [ioBroker/ioBroker.scheduler#237]
**Describe the bug**  
not all data points which are available from another adapter are available in the scheduler object tree while configuring

**Versions:**  
 - Adapter version: 1.1.9 (newest)
 -  - JS-Controller version: 18.12.1
 - Operating system: debian

**Additional context**

**Comment by Apollon77** [comment]
Please add more details, logs, screenshots? Sate whats missing ...?!

**Comment by GermanBluefox** [comment]
Your state must have according type: number for percent and temperature and boolean for On/OFF
