### ISSUE TITLE
Profile werden "doppelt" ausgewählt

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.scheduler#262]
Ich habe ein Profil versehentlich kopiert. Da ich es nicht löschen kann (siehe Issue dazu), bleibt es deaktiviert stehen.
Jetzt wollte ich das "richtige" Profil bearbeiten. Sobald ich es auswähle, wird das kopierte mit ausgewählt:

![Screenshot 2024-04-24 145418](https://github.com/ioBroker/ioBroker.scheduler/assets/45976162/bea87c7c-d61f-4d27-9a02-e1fa740f9677)

In den Objekten sieht es auch seltsam aus, da fehlt der "TN Werktag"

![Screenshot 2024-04-24 145722](https://github.com/ioBroker/ioBroker.scheduler/assets/45976162/c655f66c-21ec-4b95-9564-367d5c6f8201)

**Comment by GermanBluefox** [comment]
> Da ich es nicht löschen kann (siehe Issue dazu)

Kann irgendwie kein Issue von @Horgul123 dafür finden.

Wie sieht native vom system.adapter.scheduler.0 ?
![image](https://github.com/ioBroker/ioBroker.scheduler/assets/4582016/9ff5934f-4b44-4e46-90d7-0ec61b6e8fe7)

**Comment by Horgul123** [comment]
@GermanBluefox : Ich meinte das issue: [https://github.com/ioBroker/ioBroker.scheduler/issues/258#issuecomment-2080243211](https://github.com/ioBroker/ioBroker.scheduler/issues/258#issuecomment-2080243211)

Wie lasse ich das anzeigen, was Du benötigst? Finde das leider nicht.

**Comment by Horgul123** [comment]
@GermanBluefox Nach Tests bzgl. dem Löschen von Profilen nicht mehr vorhanden, da ich die fehlerhaften Profile löschen konnte
