### ISSUE TITLE
Zeit Schaltuhren sperren

### ISSUE THREAD

**Issue by mpl1337** [ioBroker/ioBroker.scheduler#79]
wäre es möglich eine Funktion einzubauen um einzelne Zeit Schaltuhren über ein externes Objekt bzw. gerät zu sperren?

**Comment by GermanBluefox** [comment]
Das geht schon jetzt.
Dieses Objekt steuert ob das Profile aktiv oder inaktiv ist:
![image](https://github.com/ioBroker/ioBroker.scheduler/assets/4582016/3d57c1a6-0486-43b8-ba7b-0af17407c0ea)
